### ISSUE TITLE
Am beginner in word2vec- Error in import word2vec

### ISSUE THREAD

**Issue by Rahulvks** [fbkarsdorp/doc2vec#2]
1.Tried in Ubuntu 
 svn checkout http://word2vec.googlecode.com/svn/trunk/ 
 cd trun
 Make - showing make: Nothing to be done for `all'
./demo- word and ./demo-phrases is working

 how to install in windows kindly help me with steps ?

2.When importing word2vec in python2.7

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import word2vec
  File "word2vec.py", line 14, in <module>
    model = word2vec.Word2Vec(sentences, size=100, window=4, min_count=1, workers=4)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/word2vec.py", line 432, in **init**
    self.train(sentences)
  File "/usr/local/lib/python2.7/dist-packages/gensim-0.12.3-py2.7-linux-x86_64.egg/gensim/models/word2vec.py", line 690, in train
    raise RuntimeError("you must first build vocabulary before training the model")
RuntimeError: you must first build vocabulary before training the model

Thanks in Advance

**Comment by fbkarsdorp** [comment]
I'm sorry, but for questions about Gensim you should ask the developers of that software package.
